#!/bin/bash

echo "**********"
echo ""

rm lex.yy.c y.tab.c Program

if [ "$?" -eq "0" ]
	then echo "  files deleted"
	else echo "  Not all files deleted"
fi

echo ""
echo "**********"

lex lex.l
yacc parser.y
cc -Wall print_ast.c ast.c -o Program y.tab.c -ll -Ly 

COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

./Program<text.t

COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

