#!/bin/bash
getParam=$1

echo "**********"
echo ""

rm lex.yy.c y.tab.c Program

if [ "$?" -eq "0" ]
	then echo "  files deleted"
	else echo "  Not all files deleted"
fi

echo ""
echo "**********"

lex lex.l
yacc parser.y > /dev/null 2>&1
cc -Wall print_ast.c ast.c -o Program y.tab.c -ll -Ly 

COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

if [ "$getParam" -eq "1" ]
then
	echo "*****************************************************************************************************"
        echo "Test number 1 should faild"
        echo "fail_a"
        echo "*****************************************************************************************************"
        
        ./Program<tests/fail_a.t
fi
if [ "$getParam" -eq "2" ]
then
        echo "*****************************************************************************************************"
        echo "Test number 2 should faild"
        echo "fail_b"
        echo "*****************************************************************************************************"
        ./Program<tests/fail_b.t
fi
if [ "$getParam" -eq "3" ]
then
        echo "*****************************************************************************************************"
        echo "Test number 3 should pass"
        echo "pass_a"
        echo "*****************************************************************************************************"
        ./Program<tests/pass_a.t
fi
if [ "$getParam" -eq "4" ]
then
        echo "*****************************************************************************************************"
        echo "Test number 4 should pass"
        echo "pass_b"
        echo "*****************************************************************************************************"
        ./Program<tests/pass_b.t
fi
if [ "$getParam" -eq "5" ]
then
        echo "*****************************************************************************************************"
        echo "Test number 5 should pass"
        echo "pass_c"
        echo "*****************************************************************************************************"
        ./Program<tests/pass_c.t
fi
if [ "$getParam" -eq "6" ]
then
        echo "*****************************************************************************************************"
        echo "Test number 6 should pass"
        echo "pass_d"
        echo "*****************************************************************************************************"
        ./Program<tests/pass_d.t
fi

COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

