#!/bin/bash
getParam=$1

echo "**********"
echo ""

rm lex.yy.c y.tab.c Program

if [ "$?" -eq "0" ]
	then echo "  files deleted"
	else echo "  Not all files deleted"
fi

echo ""
echo "**********"

lex lex.l > /dev/null 2>&1
yacc parser.y > /dev/null 2>&1
cc -Wall symb/symb.c ast/print_ast.c ast/ast.c -o Program y.tab.c -ll -Ly 
if [ "$?" -eq "1" ]
	then 	
        echo ""
        echo ""
	exit 1
fi



COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

if [ "$getParam" -eq "1" ]
then
	echo "*****************************************************************************************************"
        echo "Test number 1 shuld pass"
        echo "simpleTest"
        echo "*****************************************************************************************************"
        ./Program<tests/simpleTest.t
fi


COUNTER=10
until [  $COUNTER -lt 0 ]; do
        echo
        let COUNTER-=1
done

